// exerciseData.js
const exercises = {
  Powerlifting: {
    Shoulders: [
      "Overhead Press",
      "Push Press",
      "Front Plate Raise",
      "Lateral Raises",
      "Face Pulls",
      "Shrugs",
      "Upright Rows",
      "High Pulls",
      "Power Cleans",
      "Snatch",
    ],
    Chest: [
      "Bench Press",
      "Incline Bench Press",
      "Decline Bench Press",
      "Dumbbell Flyes",
      "Chest Dips",
      "Push-Ups",
      "Chest Press Machine",
      "Cable Crossover",
      "Guillotine Press",
      "Floor Press",
    ],
    Arms: [
      "Barbell Curl",
      "Dumbbell Curl",
      "Hammer Curl",
      "Tricep Dips",
      "Tricep Kickbacks",
      "Skull Crushers",
      "Close Grip Bench Press",
      "Preacher Curl",
      "Reverse Curl",
      "Concentration Curl",
    ],
    Legs: [
      "Squats",
      "Deadlifts",
      "Leg Press",
      "Lunges",
      "Calf Raises",
      "Leg Curls",
      "Hack Squats",
      "Step Ups",
      "Good Mornings",
      "Romanian Deadlifts",
    ],
    Core: [
      "Planks",
      "Russian Twists",
      "Hanging Leg Raises",
      "Woodchoppers",
      "Ab Rollouts",
      "Side Planks",
      "Mountain Climbers",
      "Reverse Crunches",
      "Cable Crunches",
      "Hollow Body Hold",
    ],
  },
  Bodybuilding: {
    Shoulders: [
      "Lateral Raises",
      "Front Raises",
      "Rear Delt Flyes",
      "Arnold Press",
      "Shoulder Press Machine",
      "Face Pulls",
      "Upright Rows",
      "High Pulls",
      "Shrugs",
      "Seated Dumbbell Press",
    ],
    Chest: [
      "Dumbbell Bench Press",
      "Incline Dumbbell Press",
      "Pec Deck Machine",
      "Chest Fly Machine",
      "Dumbbell Pullover",
      "Machine Bench Press",
      "Cable Flyes",
      "Incline Cable Flyes",
      "Smith Machine Bench Press",
      "Decline Dumbbell Flyes",
    ],
    Arms: [
      "Preacher Curl",
      "Concentration Curl",
      "EZ Bar Curl",
      "Tricep Rope Pushdowns",
      "Skull Crushers",
      "Spider Curls",
      "Tricep Kickbacks",
      "Hammer Curl",
      "Close Grip Bench Press",
      "Reverse Grip Tricep Pushdown",
    ],
    Legs: [
      "Leg Extensions",
      "Leg Curls",
      "Smith Machine Squat",
      "Hack Squat Machine",
      "Lunges",
      "Leg Press",
      "Stiff Leg Deadlifts",
      "Seated Leg Press",
      "Calf Raises",
      "Leg Press Machine Calf Raise",
    ],
    Core: [
      "Cable Crunches",
      "Leg Raises",
      "Crunches",
      "Russian Twists",
      "Hanging Leg Raises",
      "Ab Rollouts",
      "Bicycle Crunches",
      "Planks",
      "Side Plank Twists",
      "Decline Crunches",
    ],
  },
  Crossfit: {
    Shoulders: [
      "Push Jerk",
      "Split Jerk",
      "Push Press",
      "Thrusters",
      "Handstand Push-Ups",
      "Dumbbell Shoulder to Overhead",
      "Kettlebell Swings",
      "Medicine Ball Cleans",
      "Hang Power Clean",
      "Push Press",
    ],
    Chest: [
      "Muscle-Ups",
      "Ring Dips",
      "Box Jumps",
      "Chest-to-Bar Pull-Ups",
      "Burpees",
      "Wall Balls",
      "Kettlebell Snatch",
      "Toes-to-Bar",
      "Double-Unders",
      "Hand Release Push-Ups",
    ],
    Arms: [
      "Kettlebell Snatch",
      "Dumbbell Clean and Jerk",
      "Kettlebell Turkish Get-Up",
      "Box Jumps",
      "Burpees",
      "Battle Ropes",
      "Ring Rows",
      "Chin-Ups",
      "Single-Arm Dumbbell Snatch",
      "Kettlebell Swings",
    ],
    Legs: [
      "Box Jumps",
      "Pistol Squats",
      "Kettlebell Lunges",
      "Wall Balls",
      "Kettlebell Goblet Squats",
      "Jumping Lunges",
      "Box Step-Ups",
      "Kettlebell Step-Ups",
      "Jump Rope",
      "Box Squats",
    ],
    Core: [
      "Toes-to-Bar",
      "Knees-to-Elbows",
      "Hollow Rocks",
      "GHD Sit-Ups",
      "Russian Twists",
      "Medicine Ball Slams",
      "Plank Variations",
      "L-Sit",
      "Dragon Flags",
      "Windshield Wipers",
    ],
  },
};

export default exercises;
